import Meals from "@/Components/Meals";
export const metadata = {
  title: "Meals | Next Js",
  description: "Generated by create next app",
};
const page = () => {
    return (
        <div className="p-12">
            
            <h2 className="text-3xl text-center">Choose Your Meals</h2>
            <p className="text-center">Choose Your Meals By Searching...</p>
            <Meals></Meals>
        </div>
    );
};

export default page;