import { getPosts } from "@/Service/getApi";
import Link from "next/link";
export const metadata = {
  title: "Post | Next Js",
  description: "Generated by create next app",
};
const page = async() => {
    const postsData = await getPosts();
    //console.log(postsData)
    return (
        <div className="h-screen">
            <h2 className="text-2xl">All Posts</h2>
            <div className="grid grid-cols-3 gap-4">
                {
                    postsData?.slice(0,20).map((post)=>(
                        <div key={post.id} className="p-8 border-2">
                            <h3>{post.title}</h3>
                            <p>{post.body}</p>
                            <button className="border-2 bg-blue-500 rounded-2xl p-2 mt-4 text-white">
                                <Link href={`/posts/${post.id}`}>View Details</Link>
                            </button>
                        </div>
                    ))
                }
            </div>
        </div>
    );
};

export default page;